CREATE TABLE lottery_ticket (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    n1 INT NOT NULL,
    n2 INT NOT NULL,
    n3 INT NOT NULL,
    n4 INT NOT NULL,
    n5 INT NOT NULL,
    n6 INT NOT NULL,
    ticket_type VARCHAR(255) NOT NULL,
    lottery_result_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT lottery_ticket_fk FOREIGN KEY (lottery_result_id) REFERENCES lottery_result(id)
);