CREATE TABLE static_ticket (
    static_ticket_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    n1 INT NOT NULL,
    n2 INT NOT NULL,
    n3 INT NOT NULL,
    n4 INT NOT NULL,
    n5 INT NOT NULL,
    n6 INT NOT NULL,
    lps_id BIGINT UNIQUE,
    PRIMARY KEY(static_ticket_id),
    CONSTRAINT static_fk FOREIGN KEY (lps_id) REFERENCES lotto_plus_statement(lps_id)
);